### ISSUE TITLE
TypeError无法下载文件

### ISSUE THREAD

**Issue by leido** [tianxianbaobao/UCS#5]
python 2.7.6
OS: linux

Linking  计算机算法设计与分析15-16秋季_资源
http://course.ucas.ac.cn/access/content/group/117006/http:__bioinfo.ict.ac.cn_~dbu_AlgorithmCourses_CS711008Z_CS711008Z_2015.html
http://course.ucas.ac.cn/access/content/group/117006/before_the_first_class.pdf
Traceback (most recent call last):
  File "syncc.py", line 185, in <module>
    c.login()
  File "syncc.py", line 92, in login
    self.get_resource(test_url)
  File "syncc.py", line 123, in get_resource
    self.download(title, res)
  File "syncc.py", line 168, in download
    self.req.Download(f, __pwd)
  File "/home/dl11/github/UCS/HttpClient.py", line 84, in Download
    output.write(content)
TypeError: must be string or buffer, not None

**Comment by freemandealer** [comment]
这个问题我也遇到了！我在Linux下可以正常下载，可是windows下就不行，报这个错。但是你用的就是Linux呀。。。

**Comment by mengke-mk** [comment]
找到log文件，然后把log文件的后几行放上来看看吧亲

**Comment by leido** [comment]
``` bash
tail -n 100 UCS.log
```

```
                if(counter.value > 0)
                {
                    button.disabled = false;
                    button.className='enabled';
                }
                else
                {
                    button.disabled = true;
                    button.className='disabled';
                }
            }
        }

        function disableLinks()
        {
            if(document.getElementsByName)
            {
                var enabledLinks = document.getElementsByName("enabledActionLinks");
                var disabledLinks = document.getElementsByName("disabledActionLinks");
                if(enabledLinks)
                {
                    for(var i = 0; i < enabledLinks.length; i++)
                    {
                        //enabledLinks[i].innerHTML = disabledLinks[i].innerHTML;
                        enabledLinks[i].style.display="none";
                        disabledLinks[i].style.display="block";
                    }
                }           
            }
        }
        function submitform(id)
        {
            var theForm = document.getElementById(id);
            if(theForm && theForm.onsubmit)
            {
                theForm.onsubmit();
            }
            if(theForm && theForm.submit)
            {
                theForm.submit();
            }
        }
    //-->
</script>


</body></html>
Thu, 01 Oct 2015 22:40:07  syncc.py[line:143] INFO linking... 计算机算法设计与分析15-16秋季_资源
Thu, 01 Oct 2015 22:40:07  syncc.py[line:167] INFO downloading http:__bioinfo.ict.ac.cn_~dbu_AlgorithmCourses_CS711008Z_CS711008Z_2015.html
Thu, 01 Oct 2015 22:40:08  syncc.py[line:167] INFO downloading before_the_first_class.pdf
```

**Comment by mengke-mk** [comment]
手头没有win的环境，我想找你当面调，方便吗。

**Comment by leido** [comment]
我在452-1

**Comment by freemandealer** [comment]
问题解决啦，你pull最新的版本再试试吧 :)

**Comment by mengke-mk** [comment]
真的解决了吗，还没回复就这么close真的好么。

**Comment by freemandealer** [comment]
我也不想close, 我用`fix #5`作commit信息使得它自动close了。有什么解决办法吗？
